# Generated by Django 3.0.8 on 2020-09-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='weight',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='cpf',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='123456', max_length=255),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='allergies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='is_organ_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='is_pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='is_smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='limitations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='medical_record_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='plan_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='practice_exercises',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='blood_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='cellphone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
